### ISSUE TITLE
RemoveReferenceAttribute  needs to exist in a different assembly

### ISSUE THREAD

**Issue by SimonCropp** [icnocop/RemoveReference.Fody#1]
RemoveReference.Fody.dll is .net 4 and hence cannot be referenced from other run-times like PCL and WinRT

RemoveReference.Fody.dll  also has transitive references on mono.cecil assemblies which you dont want to force on your consumers

So RemoveReferenceAttribute  needs to exist in its own assembly

that is what this assembly is for https://github.com/Fody/ExtraConstraints/tree/master/ExtraConstraints

**Comment by icnocop** [comment]
Thank you! :)

Fixed in commit fb8b124b90c30c60a0dcc179435222ce778af712.
